aws:
  region: ap-southeast-1
  accessKey: NDczMjcyMzMxNjQ0
  secretKey: M2FhNjY2MDk4ZDM5YzE3MTU5MTZiZTc3MDgxYWQzMWY1NGI0ZjE2Y2JkZDQxZTAxYmQwNmEzZjNjOWZlMjBjZA==
spring:
  datasource:
    url: jdbc:mysql://<DB endpoint>:3306/<DB name>
    username: ENC(<encrypted username>)
    password: ENC(<encrypted password>)
    encryption:
      key: mySecretKey
      algorithm: PBEWithMD5AndDES
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
